language: csharp
solution: Bob.2013.Community.sln
install:
  - nuget restore Bob.2013.Community.sln
  - nuget install NUnit.Runners -OutputDirectory packages -ExcludeVersion
script:
  - xbuild /p:Configuration=Debug /p:OutDir=/home/travis/build/amacal/bob-make/build/output/ Bob.2013.Community.sln
  - mono ./packages/NUnit.Runners/tools/nunit-console.exe ./build/output/Bob.Tests.dll
  - mono ./packages/NUnit.Runners/tools/nunit-console.exe ./build/output/Bob.Tests.SpecFlow.dll